# Generated by Django 3.2.5 on 2021-11-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2017-07-10'),
            preserve_default=False,
        ),
    ]
